#!/usr/bin/env python3

import sys

def factorize(n):
    i = 2
    factors = []
    while i * i <= n:
        if n % i:
            i += 1
        else:
            n //= i
            factors.append(i)
    if n > 1:
        factors.append(n)
    return factors

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print('Usage: factors <file>')
        sys.exit(1)

    with open(sys.argv[1], 'r') as f:
        numbers = [int(line.strip()) for line in f]

    for n in numbers:
        factors = factorize(n)
        p = factors[0]
        q = n // p
        print(f'{n}={p}*{q}')

